[workspace]
name = "tldr"
version = "1.0.17"
channels = ["conda-forge"]
platforms = ["linux-64", "osx-64"]

[dependencies]
python = ">=3.11"
setuptools = ">=68.0"
wheel = "*" 
faiss = "*"
langchain = "*"
langchain-openai = "*"
langchain-community = "*"

[pypi-dependencies]
openai = ">=1.78.1"
python-docx = "*"
pypdf2 = "*"
beautifulsoup4 = "*"
pillow = ">=10.2.0"
pyyaml = ">=6.0.1"
jsonschema = ">=4.21.1"
bumpversion = "*"
build = "*"
black = "*"
reportlab = "*"
scipy = "*"
numpy = "*"
deepeval = "*"
