type: object
properties:
  agentname:
    type: object
    required:
      - description
      - system_instruction
    properties:
      description:
        type: string
        description: A helpful description for users of this role
      system_instruction:
        type: string
        description: Prompt and instructions that will be used for the role
      model:
        type: string
        description: The OpenAI model to use for this role
        enum:
          - o3
          - o3-mini
          - o1
          - o1-pro
          - o1-mini
          - gpt-4o
          - gpt-4o-mini
      temperature:
        type: number
        format: float
        minimum: 0.0
        maximum: 2.0
        description: Optional floating point value for temperature
      top_p:
        type: number
        format: float
        minimum: 0.0
        maximum: 1.0
        description: Optional floating point value for top_p
      top_k:
        type: integer
        minimum: 0
        description: Optional floating point value for top_k
      max_output_tokens:
        type: integer
        minimum: 1
        description: Integer max number of tokens to allow
      seed:
        type: integer
        description: Random seed integer value
      output_type:
        type: string
        description: Specifies the type of output the role generates, either 'text' or 'image'.
        enum:
          - text
          - image
      search_web:
        type: boolean
        description: Indicates whether the role can search the web.
      quiet:
        type: boolean
        description: Quiets stdout to be minimal and concise.
